name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: Package

    - name: Verify Downloaded Artifact
      run: |
        # List the contents of the current directory to verify the artifact is downloaded
        echo "Listing files after artifact download"
        ls -al
        echo "Listing contents of the downloaded artifact"
        ls -al  # This will show the contents of the artifact files

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/my-key.pem
        chmod 400 ~/.ssh/my-key.pem  # Set appropriate permissions for the private key

    - name: Ensure target directory exists on EC2
      run: |
        ssh -i ~/.ssh/my-key.pem ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          # Ensure /home/ubuntu/app directory exists
          sudo mkdir -p /home/ubuntu/app
          sudo chown ubuntu:ubuntu /home/ubuntu/app  # Give ownership to the ubuntu user
          # Ensure it has the correct permissions
          sudo chmod 755 /home/ubuntu/app
        EOF

    - name: Deploy code to EC2
      run: |
        # Copy the artifact to EC2 instance using scp with the private key
        scp -i ~/.ssh/my-key.pem -r staging/* ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/app

        # SSH into the EC2 instance to install dependencies and start the Java app
        ssh -i ~/.ssh/my-key.pem ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ubuntu/app
          # Check if Java is already installed, if not, install it
          java -version || sudo apt update && sudo apt install -y openjdk-17-jdk
          # Run the Java application (adjust the command as needed)
          nohup java -jar your-app.jar &
          echo "Application started."
        EOF
